# Paths
sample_file: "samples.tsv"
data_dir: "data"
results_dir: "results"

# Testing
test: True

# Performance
threads: 8

# Parameters
cutadapt:
  FWD: "CTTGGTCATTTAGAGGAAGTAA"
  REV: "GCTGCGTTCTTCATCGATGC"
  n: 2
  minimum_length: 50

# Dada2
dada2:
  maxN: 0
  maxEE: "c(6,6)"
  truncLen: 0
  truncQ: 2
  minLen: 50
  rm_phix: True