# Paths
sample_file: "samples.tsv"
data_dir: "data"
results_dir: "results"

# Performance
threads: 8

# Parameters
ITS:
  FWD: "CTTGGTCATTTAGAGGAAGTAA"
  REV: "GCTGCGTTCTTCATCGATGC"

# Preprocessing
demultiplex: True
pool: True