name: techpaper
channels:
  - bioconda
  - conda-forge
dependencies:
  - bioconductor-dada2=1.14
  - snakemake-minimal
  - r-here
  - bioconductor-biostrings
  - cutadapt=2.4
  - biopython
  - pandas
  - sra-tools