$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

# possible entries of the config file and which type they should be
properties:
  samples:
    type: string
    default: config/samples.tsv
    description: Sample file
  data_dir:
    type: string
    default: data
    description: Where to download/read raw data from


# entries that have to be in the config file for successful validation
required:
  - samples